### ISSUE TITLE
> Ongoing problem from a closed issue.

### ISSUE THREAD

**Issue by creativefibro** [alangrainger/obsidian-frontmatter-modified-date#15]
> You're talking about this message:
> 
> ![265190256-841e085a-b681-4d5e-ae15-8657b77b048b](https://private-user-images.githubusercontent.com/16197738/265190473-7465c3eb-6ae5-4b99-8817-ff048e182153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzY4ODAsIm5iZiI6MTcwNDU3NjU4MCwicGF0aCI6Ii8xNjE5NzczOC8yNjUxOTA0NzMtNzQ2NWMzZWItNmFlNS00Yjk5LTg4MTctZmYwNDhlMTgyMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIxMjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzM3ZTMxNzliNTAxYmYwNzA1NTVmMmEyNTI1OWM4YzZlZDdmYzYzYjBjNGQxMjYwZDZmMmI0N2E4YWEzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FPDu4y_NgLEHYV5_k1MdfuF_cSyaTt9mrFn8ZNMmPKg)
> 
> This is to be expected, and is due to the way Obsidian itself handles the frontmatter update. If you are typing into a note at the same time that Obsidian updates the frontmatter field, it will show that message. There is no "external" process modifying the file, it is Obsidian itself.
> 
> My plugin works by waiting for 10 seconds after you stop typing before updating the frontmatter. By doing it this way it reduces the chance of that message popping up. However, if you start typing again the exact instant Obsidian is updating the frontmatter field, you'll see that message. It won't affect anything, it's just annoying. Hopefully they resolve this at some point.
> 
> Please note that you do not need to have the file open for the frontmatter to update. The updates go into a queue and the file will update even after you close it.

I think there may be a bug with this still. You said the plugin waits for ten seconds after you stop typing before updating it. I regularly find I pause to think for a few seconds and carry on typing to  look up and see that this message has popped up and the middle of a couple of words is missing.

_Originally posted by @creativefibro in https://github.com/alangrainger/obsidian-frontmatter-modified-date/issues/3#issuecomment-1879834985_

**Comment by alangrainger** [comment]
@creativefibro as I mention, that's expected and the way that Obsidian itself handles the frontmatter update. There isn't anything that can be done to fix this, other than changing the timeout. You can edit that in the `data.json` file to increase it from 10 seconds to something that works better with your pausing-to-think timing. Change the value of the `timeout` field in `data.json` and then restart Obsidian.

**Comment by nuanjanP** [comment]
First, let me say thank you for this wonderful plugin. It helped me a lot these past months :)

Now to the topic. I encounter this popup on a regular basis, and usually I won't think too much, but today I realized there are cases where this conflict of typing and front matter updating can cause data loss. I think maybe this is what @creativefibro is conveying in the previous comment.

Concretely, the text last inserted (in my case, 4 entire lines of text, because I was rapidly copying and pasting things) disappeared right after the conflict. And multiple undos (repeated Ctrl+Z's) do seem to confirm this by bringing back the text and rewinding the last modified time.

Personally I've already edited the `timeout` field in the `jata.json` file to `90` to try to avoid this, but I thought at least I should also report this phenomenon. Hope this helps.
