### ISSUE TITLE
[Bug] External Processes Modifying file.

### ISSUE THREAD

**Issue by albertoloscerritos** [alangrainger/obsidian-frontmatter-modified-date#3]
Hi, I keep getting a message about external process modifying my file. Merging. (Not the exact words but I haven't been able to take a screenshot of the message). 
This keeps happening even after selecting Use typing events and restarting obsidian.
Do you know if this is expected behavior? Thanks.

**Comment by alangrainger** [comment]
You're talking about this message:

![265190256-841e085a-b681-4d5e-ae15-8657b77b048b](https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/16197738/7465c3eb-6ae5-4b99-8817-ff048e182153)

This is to be expected, and is due to the way Obsidian itself handles the frontmatter update. If you are typing into a note at the same time that Obsidian updates the frontmatter field, it will show that message. There is no "external" process modifying the file, it is Obsidian itself.

My plugin works by waiting for 10 seconds after you stop typing before updating the frontmatter. By doing it this way it reduces the chance of that message popping up. However, if you start typing again the exact instant Obsidian is updating the frontmatter field, you'll see that message. It won't affect anything, it's just annoying. Hopefully they resolve this at some point.

Please note that you do not need to have the file open for the frontmatter to update. The updates go into a queue and the file will update even after you close it.

**Comment by albertoloscerritos** [comment]
Thanks a lot for your answer.
One last question, would you recommend having the following option enabled o disabled?
![image](https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/16707033/c9a6b91e-d6df-4e34-a1ec-689f46037d24)

**Comment by alangrainger** [comment]
No reason at all to enable it unless you use external apps to modify files **AND** you don't want those external modifications to update your frontmatter time. Unless both those things are true, leave it off and use Obsidian's normal events system.

**Comment by albertoloscerritos** [comment]
Thanks. Now I understand :)
Have a great day.

**Comment by creativefibro** [comment]
> You're talking about this message:
> 
> ![265190256-841e085a-b681-4d5e-ae15-8657b77b048b](https://private-user-images.githubusercontent.com/16197738/265190473-7465c3eb-6ae5-4b99-8817-ff048e182153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzY4ODAsIm5iZiI6MTcwNDU3NjU4MCwicGF0aCI6Ii8xNjE5NzczOC8yNjUxOTA0NzMtNzQ2NWMzZWItNmFlNS00Yjk5LTg4MTctZmYwNDhlMTgyMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIxMjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzM3ZTMxNzliNTAxYmYwNzA1NTVmMmEyNTI1OWM4YzZlZDdmYzYzYjBjNGQxMjYwZDZmMmI0N2E4YWEzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FPDu4y_NgLEHYV5_k1MdfuF_cSyaTt9mrFn8ZNMmPKg)
> 
> This is to be expected, and is due to the way Obsidian itself handles the frontmatter update. If you are typing into a note at the same time that Obsidian updates the frontmatter field, it will show that message. There is no "external" process modifying the file, it is Obsidian itself.
> 
> My plugin works by waiting for 10 seconds after you stop typing before updating the frontmatter. By doing it this way it reduces the chance of that message popping up. However, if you start typing again the exact instant Obsidian is updating the frontmatter field, you'll see that message. It won't affect anything, it's just annoying. Hopefully they resolve this at some point.
> 
> Please note that you do not need to have the file open for the frontmatter to update. The updates go into a queue and the file will update even after you close it.

I think there may be a bug with this still. You said the plugin waits for ten seconds after you stop typing before updating it. I regularly find I pause to think for a few seconds and carry on typing to  look up and see that this message has popped up and the middle of a couple of words is missing.

**Comment by alangrainger** [comment]
@creativefibro as I mention, that's expected and the way that Obsidian itself handles the frontmatter update. There isn't anything that can be done to fix this, other than changing the timeout. You can edit that in the `data.json` file to increase it from 10 seconds to something that works better with your pausing-to-think timing. Change the value of the `timeout` field.
